language: java
jdk:
  - oraclejdk7
before_script:  
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
branches:
    only:
        - master
notifications:
  irc: "irc.freenode.org#duraspace-ff"
  email:
      - ff-tech@googlegroups.com

